== MACsec PP-Module

[cols="1,1,1,1,1,1,1,1"]
|===
8+|MACsec 
| newtransforms 
a| http://commoncriteria.github.io/MACsec/newtransforms/MACsec-release.html[📄]
a|[link=https://github.com/commoncriteria/MACsec/blob/gh-pages/newtransforms/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/MACsec/gh-pages/newtransforms/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/MACsec/blob/gh-pages/newtransforms/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/MACsec/gh-pages/newtransforms/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/MACsec/blob/gh-pages/newtransforms/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/MACsec/gh-pages/newtransforms/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/MACsec/blob/gh-pages/newtransforms/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/MACsec/gh-pages/newtransforms/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/MACsec/gh-pages/newtransforms/transforms.svg[transforms,150]
a| 
http://commoncriteria.github.io/MACsec/newtransforms/MACsec-release.html[MACsec-release.html] +
http://commoncriteria.github.io/MACsec/newtransforms/MACsec-sd.html[MACsec-sd.html] +
http://commoncriteria.github.io/MACsec/newtransforms/diff-master.html[diff-master.html] +
|===

https://github.com/commoncriteria/MACsec/issues[image:https://img.shields.io/github/issues/commoncriteria/MACsec.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Protection Profile for
QQQQ based on the
https://commoncriteria.github.io/pp/QQQQ/QQQQ-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations. A list
of products that have passed evaluation against this Protection Profile
can be found link:QQQQ[here].

=== Draft Version

* https://commoncriteria.github.io/pp/QQQQ/QQQQ-release.html[Protection
Profile for QQQQ] (html)
* https://commoncriteria.github.io/pp/QQQQ/QQQQ-release.pdf[Protection
Profile for QQQQ] (pdf)

=== Release Version

* link:QQQQ[Protection Profile for QQQQ]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/MACsec/issues[repository issue
tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/qqqq.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
